name: Testing
on: push

jobs:
  test_project:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: airline
    steps:
    - uses: actions/checkout@v2.5.0
    - name: Run Django unit tests
      run: |
        pip3 install --user django
        python3 manage.py test
