name: Testing
on: push

jobs:
  test-project:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.5.0
    - name: Run Django unit test
      run:
        pip3 install --user django
        python3 manage.py test
